-- ============================================================
-- seed.sql
-- Datos iniciales — Come en Girardota
-- IMPORTANTE: ejecutar SOLO en desarrollo o proyecto nuevo.
-- NO ejecutar en producción si ya existen usuarios.
-- ============================================================

-- ── Crear usuario admin inicial ──────────────────────────────
-- El primer usuario administrador debe crearse directamente
-- desde el Supabase Dashboard:
--   Dashboard → Authentication → Users → Invite user
--
-- Luego asignar el rol 'admin' manualmente:
--   Dashboard → Table Editor → profiles → editar el registro
--   y cambiar role a 'admin'.
--
-- NUNCA incluir credenciales en este archivo.
-- SEC-003 | 2026-04-26

-- ── Categorías de referencia ─────────────────────────────────
-- No se almacenan en la base de datos — están hardcodeadas en
-- account.model.ts como DIRECTORY_CATEGORIES.
-- Si se decide moverlas a la DB, crear una tabla aquí:
--
-- CREATE TABLE public.categories (
--   id    SERIAL PRIMARY KEY,
--   name  TEXT NOT NULL UNIQUE,
--   order INT  NOT NULL DEFAULT 0
-- );
-- INSERT INTO public.categories (name, order) VALUES
--   ('Restaurante',  1),
--   ('Comida rápida',2),
--   ('Panadería',    3),
--   ('Cafetería',    4),
--   ('Heladería',    5),
--   ('Asadero',      6),
--   ('Frutería',     7),
--   ('Postres',      8);